sudo: required
language: node_js
node_js:
  - "7"
services:
  - docker
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
- docker build --no-cache -t test-travis-docker-build .
- docker run test-travis-docker-build
